# Generated by Django 4.2.9 on 2024-02-01 12:48

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_carouselimage_category_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                null=True, upload_to=utils.utils.category_image_upload_path
            ),
        ),
    ]
